### PR TITLE
MT-PGA example

### PR DESCRIPTION
**Pull request by MatPont**
This PR adds the example for MT-PGA.

PS: For the moment the computation of FTM **is still** with 1 thread because, even with https://github.com/topology-tool-kit/ttk/pull/849, it seems to still have non-deterministic behavior...

### CODE REVIEW

**Comment by julien-tierny** [comment]
it looks like the file `earthquake_terrain.vtk` is missing. could you add that up please?

**Comment by julien-tierny** [comment]
could you please also augment the python code, in order to show case:
- how to store the geodesics of the basis
- how to reconstruct the merge trees from the basis and their coordinates in the basis?

**Comment by MatPont** [comment]
> it looks like the file `earthquake_terrain.vtk` is missing. could you add that up please?

`earthquake_terrain.vtk` is already in `ttk-data` ([earthquake_terrain.vtk](https://github.com/topology-tool-kit/ttk-data/blob/dev/earthquake_terrain.vtk)). It was added with #132. Does the paraview state file tell you that is missing?

**Comment by julien-tierny** [comment]
> > it looks like the file `earthquake_terrain.vtk` is missing. could you add that up please?
> 
> `earthquake_terrain.vtk` is already in `ttk-data` ([earthquake_terrain.vtk](https://github.com/topology-tool-kit/ttk-data/blob/dev/earthquake_terrain.vtk)). It was added with #132. Does the paraview state file tell you that is missing?

got it. paths were absolute in the pvsm file. just fixed that.
if you could take care of the python script, that'd be awesome.
(also, thanks for taking care of the warnings mentioned in https://github.com/topology-tool-kit/ttk/pull/821)

**Comment by MatPont** [comment]
> got it. paths were absolute in the pvsm file. just fixed that. if you could take care of the python script, that'd be awesome. 

Indeed, my bad for the absolute path! 
I just updated the doc and the python script to save the geodesics of the basis and compute the reconstructed trees.

> (also, thanks for taking care of the warnings mentioned in [topology-tool-kit/ttk#821](https://github.com/topology-tool-kit/ttk/pull/821))

sure!

**Comment by julien-tierny** [comment]
Screenshot_20221110_082624

**Comment by julien-tierny** [comment]
I'm unsure of the viewpoint for the geodesic surface. Is that how it's supposed to look? Is that what you had in mind?
(that's the viewpoint from the state file)

**Comment by MatPont** [comment]
Hum.. interesting.. In my computer it produces the picture attached at the end of this message.

Actually what you show is, with my computer, the *wrong* result when I enable the parallelism of `FTM`. Did you still have `threadNumber = 1` in the GUI of the filter ?

If yes, my hypothesis is that, depending on the computer (due to gcc version of things like that) the non-determinism of `FTM` will produces the *good* output or the *wrong* one. (We've already checked that the input trees can be different with parallelism)

A solution could be, of course to fix the non-determinism of `FTM`, and then to fix if needed this state file depending on the deterministic output.

Screenshot from 2022-11-09 16-34-15

**Comment by julien-tierny** [comment]
I confirm that I'm running FTM with only one thread (as specified in the pvsm file).
- have you tried to run this example on your desktop too? do you have the same result as your laptop?
- I can save the trees computed by FTM and post them here, such that you can compare them with yours (obviously the reconstructed trees are different, as seen in the views with the colored background). If our FTM outputs are identical, then it means that the non-deterministic behavior occurs further down the pipeline

**Comment by julien-tierny** [comment]
[earthquakeTrees.vtm.zip](https://github.com/topology-tool-kit/ttk-data/files/9978970/earthquakeTrees.vtm.zip)

**Comment by julien-tierny** [comment]
[earthquake.trees.zip](https://github.com/topology-tool-kit/ttk-data/files/9978988/earthquake.trees.zip)

**Comment by julien-tierny** [comment]
[earthquake.barycenter.zip](https://github.com/topology-tool-kit/ttk-data/files/9982747/earthquake.barycenter.zip)

**Comment by julien-tierny** [comment]
barycenter with 24 threads (in principle, identical to 1 thread)

**Comment by julien-tierny** [comment]
[earthquake.barycenter.zip](https://github.com/topology-tool-kit/ttk-data/files/9982774/earthquake.barycenter.zip)

**Comment by julien-tierny** [comment]
@pierre-guillou could you try to run this state file and post a screenshot of your outcome?
that'd be very helpful for us (to try to track down the origin of the non determinism)

**Comment by pierre-guillou** [comment]
With 1 thread:
image

**Comment by pierre-guillou** [comment]
With 16 threads:
image

**Comment by julien-tierny** [comment]
this is the default view (1 thread) with my desktop at the lab:
Screenshot_20221115_073605

**Comment by julien-tierny** [comment]
@MatPont 
could you sync your local repo of TTK to get pierre's latest PR (https://github.com/topology-tool-kit/ttk/pull/874) and then update this state file and post your new screenshot here? (hopefully, it should become "more" deterministic)
thanks!

**Comment by julien-tierny** [comment]
Screenshot_20221208_075058

**Comment by julien-tierny** [comment]
@MatPont I updated the camera viewpoint for the PGS (above screenshot) after @pierre-guillou's PR on MT node children re-ordering. 
could you post a screenshot of what you get after that PR? is that similar to the above screenshot?

**Comment by MatPont** [comment]
Arf.. this is not over..

The 2D layout is also different (dark red pairs at bottom left). I have this result on both computers and with 1 thread or 16 threads.

(by the way I've pulled ttk dev and this branch)

Screenshot from 2022-12-09 09-12-07

**Comment by julien-tierny** [comment]
@pierre-guillou how does this state now looks like for you? (you want to make sure to git pull this state too), thanks!

**Comment by pierre-guillou** [comment]
I've tried with 1 and 16 threads, both are identical (on my laptop).
Capture d’écran du 2022-12-09 10-03-51

**Comment by julien-tierny** [comment]
what version of scikit-learn are you guys running?
(we may end up in different local minima of MDS)

**Comment by pierre-guillou** [comment]
python-scikit-learn 1.1.3-1

**Comment by MatPont** [comment]
Since the 2D layout are also different (dark red pairs at bottom left), I suspect that the problem is not only (if it is) related to MDS but at least related to the computation of PGA (or FTM before). 
That means that the coordinates of the input trees are different after computing the PGA.

**Comment by MatPont** [comment]
Could you please @julien-tierny share the input trees (in output of the `FTM` filter) that gave you this result?
We can compare the nodes and arcs order to verify that topology-tool-kit/ttk#874 works well and otherwise try to find the source of the problem elsewhere.

**Comment by julien-tierny** [comment]
[inputTrees.zip](https://github.com/topology-tool-kit/ttk-data/files/10215384/inputTrees.zip)
There you are. Thanks!

**Comment by MatPont** [comment]
Using the trees you've shared the result does not change for me..
When you have time, could you please share the barycenter (in output of MT-PGA)?

**Comment by julien-tierny** [comment]
[barycenter.zip](https://github.com/topology-tool-kit/ttk-data/files/10226915/barycenter.zip)
there you are (sorry for the delay, got interrupted)

**Comment by MatPont** [comment]
Your barycenter and mine differ, there is at least a problem in the barycenter computation then.

**Comment by MatPont** [comment]
Hi @julien-tierny, I updated the state by taking into account https://github.com/topology-tool-kit/ttk/pull/923 (that hopefully solves the non determinism behavior). Here is a screenshot of what I have on my desktop and laptop.

Screenshot from 2023-04-20 16-32-15

**Comment by julien-tierny** [comment]
it looks very similar on my laptop, although there still are subtle differences (eg. zigzags in the purple trajectory):
Screenshot_20230422_064022

**Comment by julien-tierny** [comment]
Screenshot_20230511_123654

with the latest fix on the projection (https://github.com/MatPont/ttk/tree/projFromTableFix), it looks like the screenshots are finally identical :)

**Comment by julien-tierny** [comment]
great stuff, congrats on the perseverance ;)

**Comment by julien-tierny** [comment]
I confirm the fix on my laptop, I'll go ahead and double-check the documentation but this one looks like it's ready to ship!
thanks!

**Comment by julien-tierny** [comment]
Alright, let's go!

**Pull request merged**
