### PR TITLE
Merge tree Clustering

### PR DESCRIPTION
**Pull request by MatPont**
This PR adds a paraview state for the clustering of merge trees related to the following publication (figure 1.h):

"Wasserstein Distances, Geodesics and Barycenters of Merge Trees"
Mathieu Pont, Jules Vidal, Julie Delon, Julien Tierny.
Proc. of IEEE VIS 2021.
IEEE Transactions on Visualization and Computer Graphics, 2021

### CODE REVIEW

**Comment by julien-tierny** [comment]
some discussion is needed regarding the multiple occurrence of the clustering module.

**Comment by julien-tierny** [comment]
it seems like some more work is needed on this one, with a PR to the code (deterministic initialization with explicit random seed)

**Comment by MatPont** [comment]
The previous commits use only one clustering algorithm to find the centroids (moreover the statefile size is lower).
It needs the commits of topology-tool-kit/ttk#660 and topology-tool-kit/ttk#659.

**Comment by julien-tierny** [comment]
alright, looks good :)
thanks !

**Pull request merged**
