### PR TITLE
Add manifoldCheck example

### PR DESCRIPTION
**Pull request by lhofmann**

### CODE REVIEW

**Comment by julien-tierny** [comment]
that's looks perfect to me!!!
please don't forget to also add ` python/manifoldCheck1.py` and ` python/manifoldCheck2.py` to the PR.

**Comment by julien-tierny** [comment]
once, you're done, I'll merge your PR and put it online.
next, I'll ask you to update the doxgen documentation of the corresponding module to point to the examples.
thanks!

**Comment by julien-tierny** [comment]
for the update of the doxygen and paraview documentation, see that commit for instance:
https://github.com/topology-tool-kit/ttk/commit/2b9fd4cc43ef60f6a0460e68e4ca84c001171216

**Comment by lhofmann** [comment]
I think this is ready. On to the doxygen docs :)

**Pull request merged**
