### PR TITLE
Added example for MergeTree with ExTreeM

### PR DESCRIPTION
**Pull request by m-s-will**
This example showcases the MergeTree filter which computes the join and split tree via path compression and the ExTreeM algorithm.

Depends on ttk PR https://github.com/topology-tool-kit/ttk/pull/973.

### CODE REVIEW

**Comment by julien-tierny** [comment]
hi @m-s-will ,
that example seems broken. 
can you make sure it's running on your end?
thanks!

**Comment by m-s-will** [comment]
Hello Julien, it should run now, some of the attributes needed to be renamed after merging both merge tree algorithms.

**Comment by julien-tierny** [comment]
hi @m-s-will,
thanks a lot for your edits!

I think this example is ready to go. 
However, to make the screenshot a little nicer, would it be possible that, in the VTK layer of your merge tree implementation, you add a PointData array named "CriticalType" (see for instance the dragon example). That will allow the user to color the nodes of the merge trees based on the type of critical pint (0: minima, 1: 1-saddles, 2: 2-saddles, 3: maxima, see the VTK-layer implementation of FTM for compatibility).

Similarly, it would be nice to unify the "RegionType" segmentation scalar array from FTM with the "IsLeaf" segmentation of ExTreeM. Thanks!

**Comment by julien-tierny** [comment]
hi @m-s-will ,
I tried the critical type coloring on this example and it looks like, for the split tree, it is inverted with regard to FTM.
i.e. the join tree should have only one max, several min and several one-saddles (possibly multiple saddles)
and the split tree should have only one minimum, several max and several 2-saddles (possibly multiple saddles)
I believe these two cases should be differentiated too in ExTreeM. Could you update that really quick? Thanks a lot!

**Comment by m-s-will** [comment]
Hey Julien, did a quick PR for the oversight https://github.com/topology-tool-kit/ttk/pull/993

**Comment by julien-tierny** [comment]
wonderful, thanks a lot!

**Pull request merged**
