### PR TITLE
New Statefile and Data for ContourTreeAlignment

### PR DESCRIPTION
**Pull request by floWetzels**
I created a new statefile for the ContourTreeAlignment module which uses a cinema database containing the raw scalar fields., whereas the old statefile used two preprocessed databases containing the contour trees and the segmentations. (The reason why I used the preprocessed datasets was that I used to compute the simplification and contour tree per member with the ttkForEach filter in my old pipelines. Now I just use the multiblock functionality of the TopologicalSimplificationByPersistence and FTMTree filters, which makes the pipeline from scratch much more reasonable and readable.)

I am not sure if this is necessary and if the old statefile and datasets should be kept. I am therefore happy to recieve feedback.

Thanks
Florian

### CODE REVIEW

**Comment by floWetzels** [comment]
Any ideas on this, @julien-tierny?
I would like to do the VIS-tutorial with this kind of pipeline, so it could be nice if it concurs with the "officially" provided statfiles.

**Comment by julien-tierny** [comment]
hi florian,

thanks a lot for your PR, and thanks for the kind reminder!

the new pipeline seems reasonable to me.
I liked the idea of only processing a database of contour trees (which sounds really practical), but if the segmentation is needed as well, then there's no so much data reduction involved anymore.

so ok in principle to work from the database of raw data.
I would suggest then to replace `contourTreeAlignment.pvsm` by `contourTreeAlignment_fromRawData.pvsm`.

I noticed a few issues though (I'm using ttk's dev branch).

1. the segmentation of the green feature no longer appears in 2D data (right window)
2. I have many errors in the command line (this might be related, see one instance below)

could you have a look into that?

thanks!

```
[ForEach] [B] Iteration: ( 0 / 22 )  ///////////////////////////////////////////
[ForEach] ======================================================================
[ForEach] Extraction Mode: Block               
[ForEach] Output Type    : vtkMultiBlockDataSet
[ForEach] Indicies       : [0]                 
[ForEach] ----------------------------------------------------------------------
[ForEach] Extracting blocks [0] ......................................... [100%]
[ForEach] ======================================================================
[Extract] %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[Extract] [ERROR] FieldData does not contain array 'segmentationIDs'
(  17.879s) [paraview        ]       vtkExecutive.cxx:752    ERR| vtkPVCompositeDataPipeline (0x55ece1958e00): Algorithm ttkExtract(0x55ece1a3e810) returned failure for request: vtkInformation (0x55ece3d17230)                               
  Debug: Off                                                                    
  Modified Time: 3625511                                                        
  Reference Count: 1                                                            
  Registered Events: (none)                                                     
  Request: REQUEST_DATA                                                         
  FROM_OUTPUT_PORT: 0                                                           
  ALGORITHM_AFTER_FORWARD: 1                                                    
  FORWARD_DIRECTION: 0                                                          


(  17.900s) [paraview        ]       vtkExecutive.cxx:752    ERR| vtkCompositeDataPipeline (0x55ece3ddeaf0): Algorithm vtkPVGeometryFilter(0x55ece3cda870) returned failure for request: vtkInformation (0x55ece3ddfa60)                        
  Debug: Off                                                                    
  Modified Time: 3625552                                                        
  Reference Count: 1                                                            
  Registered Events: (none)                                                     
  Request: REQUEST_DATA_OBJECT                                                  
  FROM_OUTPUT_PORT: 0                                                           
  ALGORITHM_AFTER_FORWARD: 1                                                    
  FORWARD_DIRECTION: 0                                                          


[BlockAggregator] %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[BlockAggregator] Adding object at block index 0 ................. [0.000s|100%]
[EndFor] %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by floWetzels** [comment]
Hi Julien,
thanks for the remark, I will have a look into it with the current dev branch. Last time in august it worked fine.

I also think that a pure contour tree pipeline would be nice and it is of course possible. Unfortunately, in this scenario there would not be much to see, as the ttkContourTreeAlignement module only provides the computation of the alignment without a proper layout of the tree. Therefore on the ttk/vtk/paraview layer, a visualization of the computed matching is needed to provide any insightful results. (The tool shown in the fuzzy contour tree paper used an external java script visualization of the alignment.) What do you think, should we just provide a pure contour tree statefile without a nice visualization but as a theoretic example?

**Comment by floWetzels** [comment]
Hi Julien,
I tried to reproduce the error with the current dev branch, but on my machine it works fine. What should we do about it?

**Comment by julien-tierny** [comment]
> I tried to reproduce the error with the current dev branch, but on my machine it works fine. 
that's unfortunate. 
what version of paraview are you using?
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by floWetzels** [comment]
I used version 5.8.1

**Comment by julien-tierny** [comment]
with paraview 5.9, in your pipeline, 
- ttkArrayEditor indeed has a field data array named "segmentationIDs" on its output
- same thing for "ttkForEach"
- but "MergeBlocks" no longer has that field

that may be the issue.
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by floWetzels** [comment]
Ah thanks, I will try it with paraview 5.9 and fix the issue.

**Comment by julien-tierny** [comment]
ttk's dev branch has moved on to paraview 5.9 a while ago (last february I guess).
I'd suggest your version of paraview too :(
(some workaround may need to be done with pv5.9's "MergeBlocks")
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
awesome, thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by floWetzels** [comment]
So the problem was indeed the MergeBlocks filter of paraview 5.9. I have now changed the pipeline such that the segmentationIDs are added after the MergeBlocks filter instead of before. It now looks a bit less nice, but it is working.

**Comment by julien-tierny** [comment]
alright, I made a few edits and replaced the old state by the new one.
thanks!

**Pull request merged**
