### PR TITLE
Contour around point, data and state

### PR DESCRIPTION
**Pull request by kappe-c**
Hi. I hope this is okay.

20190625_contourAroundPoint

The data is from http://www.happimip.org under the Creative Commons License.

### CODE REVIEW

**Comment by julien-tierny** [comment]
it's looking great!
I'll try to finish the review by early next week (I have a deadline at the end of this week). thanks a lot!
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
alright, looks good!
thanks
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
hi christopher,

so I ended up editing a few things (removing absolute paths, moving .nc file to native vtk formats and all) but overall, things look great and your contribution is already featured on ttk's website :)

speaking of which, two more queries, if you have time:

1. could you take a new screenshot with a terminal with ttk's output on the left side? (like the other screenshots found there: https://topology-tool-kit.github.io/gallery.html)

2. could you make a quick video tutorial (similar to those found there: https://topology-tool-kit.github.io/tutorials.html) where you would:
- open a terminal and load your state file demo to explain what it does and what it shows
- re-open paraview and rebuild your state file pipeline from scratch (to show people how to put things together)

thanks a lot for considering this, from my experience, videos are really important to advertise features.

thanks for letting me know if you need help for anything.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by kappe-c** [comment]
Hello Julien,
sorry that I kept you waiting. I hope you approve of the following :-)

2019-07 ContourAroundPoint screenshot

[Video](https://my.pcloud.com/publink/show?code=XZniSG7Zzmd3RXDYkHyMBKahlJxLJkoee117) (1920x1080, 11 min 23 s, 253 MiB)

**Comment by julien-tierny** [comment]
hi christopher,

this is **fantastic**!
thanks a lot for this contribution! 

it is up and running on ttk's website now!

cheers,
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Pull request merged**
