### PR TITLE
New Datasets and State Files

### PR DESCRIPTION
**Pull request by JonasLukasczyk**
* New ground water dataset
* New viscous fingers dataset
* New state files for Cinema filters, GeometryApproximation, TrackingFromOverlap, NestedTrackingGraphs
* New acknowledgements

### CODE REVIEW

**Comment by julien-tierny** [comment]
Looks great, thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
hi jonas,

fyi, I removed the absolute paths from the state files.

here's what the state files look like on my end.

for the cinemaReader, I'm not sure of what I should be visualizing. I was expecting to see your awesome nested tracking graph.
can you confirm you have the same thing on your end?
can you explain a little bit how to play with that example?

thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JonasLukasczyk** [comment]
Hi Julien,
I don't see any images, but the state files should show the following:
CinemaReaader: Just some slices of the viscous finger dataset
GeometryApproximation: The approximation vs the ground truth of the ground water dataset
TrackingFromOverlap: a common tracking graph showing the branches by color
NestedTrackingGraph: a nested tracking graph where at the top the colors encode levels, and at the bottom the colors encode branches for the highest level

Can you confirm this?

Best
Jonas

**Comment by julien-tierny** [comment]
alright, my bad.
I didn't see the last too.

> CinemaReaader: Just some slices of the viscous finger dataset
that's what I see indeed.
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Pull request merged**
